### ISSUE TITLE
How to get pretrained backbones for RGB and skeleton modalities

### ISSUE THREAD

**Issue by JiankunW** [juanmanpr/mfas#10]
Hi~
Thank you for sharing such a great job!
I plan to search an architecture on my own dataset, so I want to know how to get pretrained backbones models, like rgb_8frames_83.91.checkpoint and skeleton_32frames_85.24.checkpoint in your work.

**Comment by jperezrua** [comment]
Hi Jianku

Basically you pretrain them. Each modality on its own first.
