### ISSUE TITLE
AV-MNIST Dataset

### ISSUE THREAD

**Issue by afzalxo** [juanmanpr/mfas#12]
Hi, I am unable to find the AV-MNIST dataset online. Could you kindly share a link? I am just starting out so am hoping to start with a less complex dataset.

Thanks

**Comment by HuiqinWu** [comment]
Can you find the link of AV-MNIST dataset? I met the same problem.

**Comment by vielzeuf** [comment]
Please feel free to contact the first authors of the paper by mail.
Best regards

**Comment by HuiqinWu** [comment]
https://github.com/slyviacassell/_MFAS

**Comment by HuiqinWu** [comment]
the implement of AV-MNIST

**Comment by afzalxo** [comment]
> https://github.com/slyviacassell/_MFAS

This is great! Thanks.

**Comment by HuiqinWu** [comment]
> > https://github.com/slyviacassell/_MFAS
> 
> This is great! Thanks.

@europa1610 But there is some bugs in the avmnist_gen code, have you successfully generate the data?

**Comment by afzalxo** [comment]
Hi @HuiqinWu. I faced some very minor issues while generating the dataset, e.g. creating some directories manually. But I am able to generate the data. If you could kindly be more specific as to the exact problem you're facing, I could help you out.

**Comment by HuiqinWu** [comment]
Can you give me your email address? Just for Scholarly Communication.

**Comment by afzalxo** [comment]
> Can you give me your email address? Just for Scholarly Communication.

Sure.

**Comment by europa1610** [comment]
> Can you give me your email address? Just for Scholarly Communication.

It's aahmadaa@connect.ust.hk. Talk to you soon.

**Comment by afzalxo** [comment]
Closing this issue for now. Feel free to reopen if needed.
