### ISSUE TITLE
RuntimeError: Error(s) in loading state_dict for Searchable_Skeleton_Image_Net:

### ISSUE THREAD

**Issue by oussamaabdulhay** [juanmanpr/mfas#14]
Unexpected key(s) in state_dict: "fusion_layers.0.2.weight", "fusion_layers.0.2.bias", "fusion_layers.0.2.running_mean", "fusion_layers.0.2.running_var", "fusion_layers.0.2.num_batches_tracked", "fusion_layers.1.2.weight", "fusion_layers.1.2.bias", "fusion_layers.1.2.running_mean", "fusion_layers.1.2.running_var", "fusion_layers.1.2.num_batches_tracked", "fusion_layers.2.2.weight", "fusion_layers.2.2.bias", "fusion_layers.2.2.running_mean", "fusion_layers.2.2.running_var", "fusion_layers.2.2.num_batches_tracked", "fusion_layers.3.2.weight", "fusion_layers.3.2.bias", "fusion_layers.3.2.running_mean", "fusion_layers.3.2.running_var", "fusion_layers.3.2.num_batches_tracked".

I am testing the network you provided, i am getting the above error regarding the fusion layer weights. 

Could you please provide a checkpoint file that has the fusion layer weights as well.

**Comment by jperezrua** [comment]
Hi, are you sure you are instantiating the correct model?
I checked the provided checkpoints manually and got this:

`>>> a = torch.load('long_filename.checkpoint', map_location=torch.device('cpu'))`
`>>> print([k for k in a.keys() if 'fusion' in k])`
`['fusion_layers.0.0.weight', 'fusion_layers.0.0.bias', 'fusion_layers.0.2.weight', 'fusion_layers.0.2.bias', 'fusion_layers.0.2.running_mean', 'fusion_layers.0.2.running_var', 'fusion_layers.0.2.num_batches_tracked', 'fusion_layers.1.0.weight', 'fusion_layers.1.0.bias', 'fusion_layers.1.2.weight', 'fusion_layers.1.2.bias', 'fusion_layers.1.2.running_mean', 'fusion_layers.1.2.running_var', 'fusion_layers.1.2.num_batches_tracked', 'fusion_layers.2.0.weight', 'fusion_layers.2.0.bias', 'fusion_layers.2.2.weight', 'fusion_layers.2.2.bias', 'fusion_layers.2.2.running_mean', 'fusion_layers.2.2.running_var', 'fusion_layers.2.2.num_batches_tracked', 'fusion_layers.3.0.weight', 'fusion_layers.3.0.bias', 'fusion_layers.3.2.weight', 'fusion_layers.3.2.bias', 'fusion_layers.3.2.running_mean', 'fusion_layers.3.2.running_var', 'fusion_layers.3.2.num_batches_tracked']`

All the fusion layers are in there. Please double check your code.
