### ISSUE TITLE
Git Clone failed due to using the reserved name as a folder name on windows

### ISSUE THREAD

**Issue by slyviacassell** [juanmanpr/mfas#2]
Hi, juanmanpr, thank you for your open source MFAS. But I encounter a bug when I clone your repository on windows. The details of the bug are shown in the follow:
```bash
Cloning into 'mfas'...
remote: Enumerating objects: 63, done.
remote: Counting objects: 100% (63/63), done.
remote: Compressing objects: 100% (55/55), done.
remote: Total 63 (delta 20), reused 38 (delta 6), pack-reused 0
Unpacking objects: 100% (63/63), done.
fatal: cannot create directory at 'models/aux': Invalid argument
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'
```

This bug is caused by the forbidden file name you used in your repository. Here is what MicroSoft said:

> Do not use the following reserved names for the name of a file: CON, PRN, AUX, NUL, COM1, COM2, COM3, COM4, COM5, COM6, COM7, COM8, COM9, LPT1, LPT2, LPT3, LPT4, LPT5, LPT6, LPT7, LPT8, and LPT9. Also avoid these names followed immediately by an extension; for example, NUL.txt is not recommended. For more information, see Namespaces.

So I hope you can rename the folder **model/aux**. Thanks!

**Comment by slyviacassell** [comment]
The bug is fixed in this pull [request](https://github.com/juanmanpr/mfas/pull/4).

**Comment by jperezrua** [comment]
Thanks, I have accepted the pull request and am closing this issue.
