### ISSUE TITLE
Search an architecture on custom dataset

### ISSUE THREAD

**Issue by zhulishun** [juanmanpr/mfas#5]
Hi~
Thank you for sharing such a great job!
I want to know how to use MFAS to search an architecture on my custom datasets, such as RGB and infrared images.

**Comment by jperezrua** [comment]
Hi @zhulishun , I think the best way for you to start is by taking a look at different specializations of the ModelSearcher class in [here](https://github.com/juanmanpr/mfas/blob/master/models/searchable.py).

You will have to add the corresponding dataloaders and backbone models and so on.

**Comment by zhulishun** [comment]
@juanmanpr  Thanks a lot.

**Comment by abhishektyaagi** [comment]
@zhulishun Did you try out MFAS on a custom dataset?

**Comment by abhishektyaagi** [comment]
@jperezrua Is it possible for you to elaborate a bit on using MFAS framework with our own custom dataset? 
I looked at the ModelSearcher class mentioned [here](https://github.com/jperezrua/mfas/blob/master/models/searchable.py).
I understand that there exists one class for each of the datasets. 

Now if I want to add my own dataset and want to search for some architectures on it, what do you recommend I should look at as my next step?
