### ISSUE TITLE
prepare NTU RGB+D dataset

### ISSUE THREAD

**Issue by zhulishun** [juanmanpr/mfas#7]
I downloaded the dataset according to your instructions, but I stuck in "change all video clips resolution to 256x256 30fps and copy them to  / ntrgbd"_ rgb/avi_ 256x256_ 30/ directory.”How can I change all video clips resolution to 256x256 30fps?
Thank you in advance for your answer.

**Comment by vielzeuf** [comment]
You can follow this preprocessing pipeline: https://github.com/fabienbaradel/glimpse_clouds/blob/master/src/data/preprocessing/rescale_videos.py
